### ISSUE TITLE
snt_pipeline is not available

### ISSUE THREAD

**Issue by ali-vosoughi** [sachit-menon/generating-illustrated-instructions-reproduction#2]
Hi Sachit, 

I'm encountering this error,

raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/v0.19.0/examples/community/snt_pipeline.py

Could you kindly check if this is a public link?
Thanks a bunch!

**Comment by ali-vosoughi** [comment]
A follow-up, that problem is resolved. I noticed that in quick_inference.py the following line refers to model that does not exist. 

for i in range(cfg.model.sequence_length):

**Comment by cloverGithub** [comment]
Hi @sachit-menon , thanks for the link, but i am still unclear on how to resolve.
Hi @ali-vosoughi, may i understand how did you resolved? 

The line with issue is pipeline = DiffusionPipeline.from_pretrained("sachit-menon/illustrated_instructions", custom_pipeline="snt_pipeline", trust_remote_code=True)

Thanks.

**Comment by ali-vosoughi** [comment]
> Hi @sachit-menon , thanks for the link, but i am still unclear on how to resolve. Hi @ali-vosoughi, may i understand how did you resolved?
> 
> The line with issue is pipeline = DiffusionPipeline.from_pretrained("sachit-menon/illustrated_instructions", custom_pipeline="snt_pipeline", trust_remote_code=True)
> 
> Thanks.

Thanks for asking @cloverGithub @sachit-menon , the problem is caused by diffuser 0.19.0, to solve that, please do the following
- After you installed requirements.txt, please run this

pip install --upgrade diffusers[torch]
