### ISSUE TITLE
Error with quick inference

### ISSUE THREAD

**Issue by cloverGithub** [sachit-menon/generating-illustrated-instructions-reproduction#3]
Hi, i encountered the following issues. Seek your advise. Thanks.

Could not locate the pipeline.py inside snt_pipeline.
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/illust/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/home/user/anaconda3/envs/illust/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/v0.19.0/examples/community/snt_pipeline.py

**Comment by sachit-menon** [comment]
It appears #2 solved this issue -- it may require a change to the line referenced there, removing the .model, but I'm not sure without further information.

**Comment by ali-vosoughi** [comment]
Thanks for asking @cloverGithub @sachit-menon , the problem is caused by diffuser 0.19.0, to solve that, please do the following
- After you installed requirements.txt, please run this

pip install --upgrade diffusers[torch]

**Comment by ali-vosoughi** [comment]
Adding to that, I had next error,

```
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
        

```

**Comment by ali-vosoughi** [comment]
How I solved, 

pip uninstall bitsandbytes
pip install bitsandbytes==0.41.0

**Comment by sachit-menon** [comment]
That error is dependent on the particular system, thanks for catching it!
